[package]
name = "librairie"
version = "0.1.0"
edition = "2024"


[lib]
name = "librairie"
crate-type = ["rlib"]


[dependencies]
rand = "0.10.0-rc.0"
colored = "2.0"
crossterm = "0.29.0"
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.145"

