[package]
name = "mot"
version = "0.1.0"
edition = "2024"

[dependencies]
rand = "0.10.0-rc.0"
colored = "2.0"
crossterm = "0.29.0"
tokio = { version = "1.48.0", features = ["full"] }
crossbeam-channel = "0.5.15"
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.145"

